# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_no', models.CharField(max_length=30, unique=True)),
                ('inward_date', models.DateField()),
                ('source_name', models.CharField(max_length=200)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('challan_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='inward_docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inward Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=20)),
                ('initial_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('unknown', 'Unknown')], max_length=20)),
                ('batch_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('inward_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inward.inwardentry')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.routermodel')),
            ],
            options={
                'ordering': ['serial_number'],
            },
        ),
    ]
