# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packed_at', models.DateTimeField(auto_now_add=True)),
                ('box_no', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('packed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('router_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='inventory.routerunit')),
            ],
            options={
                'ordering': ['-packed_at'],
            },
        ),
    ]
