# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_no', models.CharField(max_length=30, unique=True)),
                ('dispatch_date', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('transporter', models.CharField(max_length=100)),
                ('vehicle_no', models.CharField(blank=True, max_length=30)),
                ('challan_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dispatch Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch.dispatchentry')),
                ('router_unit', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_item', to='inventory.routerunit')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
