# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('body_condition', models.BooleanField(default=False)),
                ('serial_verified', models.BooleanField(default=False)),
                ('mac_verified', models.BooleanField(default=False)),
                ('performance_ok', models.BooleanField(default=False)),
                ('ports_ok', models.BooleanField(default=False)),
                ('label_ok', models.BooleanField(default=False)),
                ('qc_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('remarks', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('router_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qc_checks', to='inventory.routerunit')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
    ]
