# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StageMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail'), ('rework', 'Rework'), ('', '—')], max_length=20)),
                ('ref_type', models.CharField(blank=True, max_length=30)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing', to='masters.stagemaster')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('router_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.routerunit')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming', to='masters.stagemaster')),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
    ]
