# Generated by Django 4.2.29 on 2026-04-05 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('is_retest', models.BooleanField(default=False)),
                ('power_ok', models.BooleanField(default=False)),
                ('boot_ok', models.BooleanField(default=False)),
                ('wifi_ok', models.BooleanField(default=False)),
                ('lan_ok', models.BooleanField(default=False)),
                ('led_ok', models.BooleanField(default=False)),
                ('adapter_ok', models.BooleanField(default=False)),
                ('firmware_ok', models.BooleanField(default=False)),
                ('reset_button_ok', models.BooleanField(default=False)),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10)),
                ('fail_reason', models.CharField(blank=True, max_length=300)),
                ('remarks', models.TextField(blank=True)),
                ('router_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='inventory.routerunit')),
                ('tested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
